model:
  default: kimi-k2.7-code
  provider: ollama-cloud
  base_url: https://ollama.com/v1
agent:
  max_turns: 150
web:
  backend: firecrawl
browser:
  cloud_provider: local
display:
  tool_progress: all
computer_use:
  backend: cua
_config_version: 38
session_reset:
  mode: none
platform_toolsets:
  cli:
    - bfl
    - browser
    - clarify
    - code_execution
    - computer_use
    - cronjob
    - delegation
    - file
    - image_gen
    - memory
    - session_search
    - skills
    - terminal
    - todo
    - tts
    - vision
    - web
known_plugin_toolsets:
  cli:
    - a2a
    - spotify
known_builtin_toolsets:
  cli:
    - bfl
    - browser
    - clarify
    - code_execution
    - computer_use
    - context_engine
    - cronjob
    - delegation
    - discord
    - discord_admin
    - file
    - homeassistant
    - image_gen
    - memory
    - session_search
    - skills
    - spotify
    - stt
    - terminal
    - todo
    - tts
    - video
    - video_gen
    - vision
    - web
    - x_search
    - yuanbao
